# Generated by Django 3.2.13 on 2022-12-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_platform', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=256, null=True)),
                ('account_name', models.CharField(max_length=256, null=True)),
                ('currency', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('permissions', models.CharField(max_length=256, null=True)),
                ('refresh_token', models.CharField(max_length=256)),
                ('refresh_token_expiry', models.DateTimeField(null=True)),
                ('access_token', models.CharField(max_length=256)),
                ('access_token_expiry', models.DateTimeField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
