# Generated by Django 3.2.13 on 2022-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizations',
            options={'ordering': ['-date_time']},
        ),
    ]
